name: Update Tool Screenshots

on:
  workflow_dispatch:  # 手動実行のみ（テスト用）

jobs:
  update-screenshots:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
    
    - name: Test workflow
      run: |
        echo "Workflow is working!"
        echo "Next step: Add screenshot generation logic"